version: '3.5'
services:
  app_db:
    image: mariadb:10.1.34
    container_name: app_db
    hostname: app_db
    restart: always
    environment:
      MYSQL_DATABASE: app_admin
      MYSQL_HOST: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: app_db
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
    - appnetwork

  app_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_backend
    hostname: app_backend
    domainname: app_backend.com
    restart: always
    environment:
      MYSQL_DATABASE: app_admin
      MYSQL_HOST: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: app_db
    command: bash -c "sleep 10  && python /app/backend/manage.py runserver 0.0.0.0:8008"
    ports:
      - 8008:8008
    networks:
      - appnetwork
    volumes:
      - .:/app
    depends_on:
      - app_db

networks:
  appnetwork:
    external: true
    name: app-network


